### ISSUE TITLE
Clarify how authentication messages are computed 

### ISSUE THREAD

**Issue by ghedo** [tlswg/certificate-compression#14]
From @seanturner 
```
Is it worth expanding a bit on the text quoted above to note that it’s more than just altering the message it’s also about changing how the authentication messages are computed?  E.g., CertificateVerify is now Transcript-Hash(Handshake Context, CompressedCertificate).
```

**Comment by seanturner** [comment]
I was probably not very clear when I wrote this earlier.  Let me take another stab at it.

[RFC8446](https://datatracker.ietf.org/doc/rfc8446/) §4.4.1 includes the following:

    For concreteness, the transcript hash is always taken from the
    following sequence of handshake messages, starting at the first
    ClientHello and including only those messages that were sent:
    ClientHello, HelloRetryRequest, ClientHello, ServerHello,
    EncryptedExtensions, server CertificateRequest, server Certificate,
    server CertificateVerify, server Finished, EndOfEarlyData, client
    Certificate, client CertificateVerify, client Finished.

This draft introduces a new message that I assume would become part of the transcript hash.  Rather, it would replace the server Certificate and potentially also client Certificate because the above quote says "only those messages that were sent" and this specification is about replacing the server/client Certificate messages with the server/client CompressedCertificate message. So, it seems like we need some text that says what to do when generating/processing the transcript hash.

**Comment by seanturner** [comment]
I talked to a Chris and he's convince me this isn't a thing.
