### ISSUE TITLE
Consider expanding compression code points registry

### ISSUE THREAD

**Issue by ghedo** [tlswg/certificate-compression#15]
@knekritz suggested expanding the compression code point from 1 byte to 2.

**Comment by vasilvv** [comment]
Do we really want to do that?  I can write up a PR, but I don't really see us ever having more than 20 of those...

Old compression types took up only one byte; I expect us to have more, because dictionaries, but not much more, because realistically there are only so many codepoints we can deploy.

**Comment by ghedo** [comment]
Since it was mentioned at the meeting I thought I create an issue so it can be discussed.

I'm fine closing since I agree we probably don't need this, unless @knekritz or someone else has a reason for doing this (and we can reopen later if needed).

**Comment by knekritz** [comment]
I suggested expanding this due to the potential future use of dictionaries. I agree we will likely never have more than 20 standardized code points, but 1 byte is a bit low for experimental use without worry of collision. 1 byte is probably enough, but 2 bytes would definitely be enough, and the cost of 1 extra byte seems pretty low to me.

**Comment by vasilvv** [comment]
Fixed in #17.
